---
title: "data clean"
author: "Xiaoyang Li"
date: "2020/10/28"
output: 
  html_document:
      df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Import

```{r}
demo = read_csv("./data/Curated_Data_Cuts_Files/PPMI_Original_Cohort_BL_to_Year_5_Dataset_Apr2020.csv") %>% select("PATNO", "EVENT_ID", "APPRDX", "HISPLAT", "race") %>% 
  mutate(APPRDX = recode(APPRDX, "1"="PD", "2"="HC", "3"="SWEDD"),
         HISPLAT = recode(HISPLAT, "1"="Hispanic", "2"="HISPLAT2"),
         race= recode(race, "1"="race1", "2"="race2", "3"="race3", "4"="race4"))
  
```


### prim diag


```{r}
diag = read_csv("./data/Study_Enrollment/Primary_Diagnosis.csv") %>% select("PATNO", "EVENT_ID","PRIMDIAG") %>%
  mutate(PRIMDIAG = recode(PRIMDIAG, "17"="No pd no other", "01" = "pd", "97" = "Other"))
```


### olfactory
subject id

```{r}
scent = read_csv("./data/Non-motor_Assessments/University_of_Pennsylvania_Smell_ID_Test.csv") %>% select("PATNO", "EVENT_ID", "UPSITBK1", "UPSITBK2", "UPSITBK3", "UPSITBK4" ) %>% 
  mutate(booklet1 = case_when(UPSITBK1 > 5 ~ "booklet1_1",
                              UPSITBK1 <= 5 ~ "booklet1_0"),
         booklet2 = case_when(UPSITBK2 > 5 ~ "booklet2_1",
                              UPSITBK2 <= 5 ~ "booklet2_0"),
         booklet3 = case_when(UPSITBK3 > 5 ~ "booklet3_1",
                              UPSITBK3 <= 5 ~ "booklet3_0"),
         booklet4 = case_when(UPSITBK4 > 5 ~ "booklet4_1",
                              UPSITBK4 <= 5 ~ "booklet4_0")) %>% 
  select(-c("UPSITBK1", "UPSITBK2", "UPSITBK3", "UPSITBK4"))
```

### non-motor:moca

```{r}
moca = read_csv("./data/Non-motor_Assessments/Montreal_Cognitive_Assessment__MoCA_.csv") %>% select("PATNO", "EVENT_ID", "MCAALTTM", "MCACUBE", "MCACLCKC", "MCACLCKN", "MCACLCKH", "MCALION", "MCARHINO", "MCACAMEL", "MCAFDS", "MCABDS", "MCAVIGIL", "MCASER7", "MCASNTNC", "MCAVFNUM", "MCAVF", "MCAABSTR", "MCAREC1", "MCAREC2", "MCAREC3", "MCAREC4", "MCAREC5", "MCADATE", "MCAMONTH", "MCAYR", "MCADAY", "MCAPLACE", "MCACITY", "MCATOT") %>% 
  mutate(MCAALTTM = case_when(MCAALTTM == 1 ~ "MCAALTTM_1",
                              MCAALTTM == 0 ~ "MCAALTTM_0"),
         mcvc1 = case_when(MCACUBE == 1 ~ "mcvc1_1",
                           MCACUBE == 0 ~ "mcvc1_0"),
         mcvc2 = case_when(MCACLCKC == 1 ~ "mcvc2_1",
                           MCACLCKC == 0 ~ "mcvc2_0"),
         mcvc3 = case_when(MCACLCKN == 1 ~ "mcvc3_1",
                           MCACLCKN == 0 ~ "mcvc3_0"),
         mcvc4 = case_when(MCACLCKH == 1 ~ "mcvc4_1",
                           MCACLCKH == 0 ~ "mcvc4_0"),
         mcnm1 = case_when(MCALION == 1 ~ "mcvc1_1",
                           MCALION == 0 ~ "mcvc1_0"),
         mcnm2 = case_when(MCARHINO == 1 ~ "mcvc2_1",
                           MCARHINO == 0 ~ "mcvc2_0"),
         mcnm3 = case_when(MCACAMEL == 1 ~ "mcvc3_1",
                           MCACAMEL == 0 ~ "mcvc3_0"),
         mcatt1 = case_when(MCAFDS == 1 ~ "mcatt1_1",
                           MCAFDS == 0 ~ "mcatt1_0"),
         mcatt2 = case_when(MCABDS == 1 ~ "mcatt2_1",
                           MCABDS == 0 ~ "mcatt2_0"),
         mcatt3 = case_when(MCAVIGIL == 1 ~ "mcatt3_1",
                           MCAVIGIL == 0 ~ "mcatt3_0"),
         mcatt4 = case_when(MCASER7 >= 2 ~ "mcatt4_1",
                           MCASER7 <2 ~ "mcatt4_0"),
         mclang1 = case_when(MCASNTNC >= 2 ~ "mclang1_1",
                           MCASNTNC <2 ~ "mclang1_0"),
         mclang2 = case_when(MCAVFNUM >= 20 ~ "mclang1_1",
                           MCAVFNUM <20 ~ "mclang1_0"),
         mclang3 = case_when(MCAVF == 1 ~ "mcatt3_1",
                           MCAVF == 0 ~ "mcatt3_0"),
         mcabs = case_when(MCAABSTR >= 2 ~ "mcatt3_1",
                           MCAABSTR < 2 ~ "mcatt3_0"),
         mcdr1 = case_when(MCAREC1 == 1 ~ "mcdr1_1",
                           MCAREC1 == 0 ~ "mcdr1_0"),
         mcdr2 = case_when(MCAREC2 == 1 ~ "mcdr2_1",
                           MCAREC2 == 0 ~ "mcdr2_0"),
         mcdr3 = case_when(MCAREC3 == 1 ~ "mcdr3_1",
                           MCAREC3 == 0 ~ "mcdr3_0"),
         mcdr4 = case_when(MCAREC4 == 1 ~ "mcdr4_1",
                           MCAREC4 == 0 ~ "mcdr4_0"),
         mcdr5 = case_when(MCAREC5 == 1 ~ "mcdr5_1",
                           MCAREC5 == 0 ~ "mcdr5_0"),
         mcori1 = case_when(MCADATE == 1 ~ "mcori1_1",
                           MCADATE == 0 ~ "mcori1_0"),
         mcori2 = case_when(MCAMONTH == 1 ~ "mcori2_1",
                           MCAMONTH == 0 ~ "mcori2_0"),
         mcori3 = case_when(MCAYR == 1 ~ "mcori3_1",
                           MCAYR == 0 ~ "mcori3_0"),
         mcori4 = case_when(MCADAY == 1 ~ "mcori4_1",
                           MCADAY == 0 ~ "mcori4_0"),
         mcori5 = case_when(MCAPLACE == 1 ~ "mcori5_1",
                           MCAPLACE == 0 ~ "mcori5_0"),
         mcori6 = case_when(MCACITY == 1 ~ "mcori6_1",
                           MCACITY == 0 ~ "mcori6_0"),
         mctot = case_when(MCATOT >= 15 ~ "mcori6_1",
                           MCATOT < 15 ~ "mcori6_0")
         ) %>% 
  select(-c("MCAALTTM", "MCACUBE", "MCACLCKC", "MCACLCKN", "MCACLCKH", "MCALION", "MCARHINO", "MCACAMEL", "MCAFDS", "MCABDS", "MCAVIGIL", "MCASER7", "MCASNTNC", "MCAVFNUM", "MCAVF", "MCAABSTR", "MCAREC1", "MCAREC2", "MCAREC3", "MCAREC4", "MCAREC5", "MCADATE", "MCAMONTH", "MCAYR", "MCADAY", "MCAPLACE", "MCACITY"))
```

### motor
```{r}
updrs1 = read_csv("./data/Motor___MDS-UPDRS/MDS_UPDRS_Part_I.csv") %>% select("PATNO", "EVENT_ID",  "NP1COG", "NP1HALL", "NP1DPRS", "NP1ANXS", "NP1APAT", "NP1DDS") %>% 
  mutate(NP1COG = case_when(NP1COG >=3 ~ "NP1COG_1",
                           NP1COG < 3 ~ "NP1COG_0"),
         NP1HALL = case_when(NP1HALL >=3 ~ "NP1HALL_1",
                           NP1HALL < 3 ~ "NP1HALL_0"),
         NP1DPRS = case_when(NP1DPRS >=3 ~ "NP1DPRS_1",
                           NP1DPRS < 3 ~ "NP1DPRS_0"),
         NP1ANXS = case_when(NP1ANXS >=3 ~ "NP1ANXS_1",
                           NP1ANXS < 3 ~ "NP1ANXS_0"),
         NP1APAT = case_when(NP1APAT >=3 ~ "NP1APAT_1",
                           NP1APAT < 3 ~ "NP1APAT_0"),
         NP1DDS = case_when(NP1DDS >=3 ~ "NP1DDS_1",
                           NP1DDS < 3 ~ "NP1DDS_0"))


updrs1pq = read_csv("./data/Motor___MDS-UPDRS/MDS_UPDRS_Part_I__Patient_Questionnaire.csv") %>% select("PATNO", "EVENT_ID", "NP1SLPN", "NP1SLPD", "NP1PAIN", "NP1URIN", "NP1CNST", "NP1LTHD", "NP1FATG")%>% 
  mutate(NP1SLPN = case_when(NP1SLPN >=3 ~ "NP1SLPN_1",
                           NP1SLPN < 3 ~ "NP1SLPN_0"),
         NP1SLPD = case_when(NP1SLPD >=3 ~ "NP1SLPD_1",
                           NP1SLPD < 3 ~ "NP1SLPD_0"),
         NP1PAIN = case_when(NP1PAIN >=3 ~ "NP1PAIN_1",
                           NP1PAIN < 3 ~ "NP1PAIN_0"),
         NP1URIN = case_when(NP1URIN >=3 ~ "NP1URIN_1",
                           NP1URIN < 3 ~ "NP1URIN_0"),
         NP1CNST = case_when(NP1CNST >=3 ~ "NP1CNST_1",
                           NP1CNST < 3 ~ "NP1CNST_0"),
         NP1LTHD = case_when(NP1LTHD >=3 ~ "NP1LTHD_1",
                           NP1LTHD < 3 ~ "NP1LTHD_0"),
         NP1FATG = case_when(NP1FATG >=3 ~ "NP1FATG_1",
                           NP1FATG < 3 ~ "NP1FATG_0"))

updrs2pq = read_csv("./data/Motor___MDS-UPDRS/MDS_UPDRS_Part_II__Patient_Questionnaire.csv")%>% select("PATNO", "EVENT_ID", "NP2SPCH", "NP2SALV", "NP2SWAL", "NP2EAT", "NP2DRES", "NP2HYGN", "NP2HWRT", "NP2HOBB", "NP2TURN", "NP2TRMR", "NP2RISE", "NP2WALK", "NP2FREZ") %>% 
  mutate(
    NP2SPCH = case_when(NP2SPCH >=3 ~ "NP2SPCH_1",
                           NP2SPCH < 3 ~ "NP2SPCH_0"),
    NP2SALV = case_when(NP2SALV >=3 ~ "NP2SALV_1",
                           NP2SALV < 3 ~ "NP2SALV_0"),
    NP2SWAL = case_when(NP2SWAL >=3 ~ "NP2SWAL_1",
                           NP2SWAL < 3 ~ "NP2SWAL_0"),
    NP2EAT = case_when(NP2EAT >=3 ~ "NP2EAT_1",
                           NP2EAT < 3 ~ "NP2EAT_0"),
    NP2DRES = case_when(NP2DRES >=3 ~ "NP2DRES_1",
                           NP2DRES < 3 ~ "NP2DRES_0"),
    NP2HYGN = case_when(NP2HYGN >=3 ~ "NP2HYGN_1",
                           NP2HYGN < 3 ~ "NP2HYGN_0"),
    NP2HWRT = case_when(NP2HWRT >=3 ~ "NP2HWRT_1",
                           NP2HWRT < 3 ~ "NP2HWRT_0"),
    NP2HOBB = case_when(NP2HOBB >=3 ~ "NP2HOBB_1",
                           NP2HOBB < 3 ~ "NP2HOBB_0"),
    NP2TURN = case_when(NP2TURN >=3 ~ "NP2TURN_1",
                           NP2TURN < 3 ~ "NP2TURN_0"),
    NP2TRMR = case_when(NP2TRMR >=3 ~ "NP2TRMR_1",
                           NP2TRMR < 3 ~ "NP2TRMR_0"),
    NP2RISE = case_when(NP2RISE >=3 ~ "NP2RISE_1",
                           NP2RISE < 3 ~ "NP2RISE_0"),
    NP2WALK = case_when(NP2WALK >=3 ~ "NP2WALK_1",
                           NP2WALK < 3 ~ "NP2WALK_0"),
    NP2FREZ = case_when(NP2FREZ >=3 ~ "NP2FREZ_1",
                           NP2FREZ < 3 ~ "NP2FREZ_0")
  )

# fail to find "CMEDTM"
updrs3 = read_csv("./data/Motor___MDS-UPDRS/MDS_UPDRS_Part_III.csv")%>% select("PATNO", "EVENT_ID", "NP3SPCH", "NP3FACXP", "NP3RIGN", "NP3RIGRU", "NP3RIGLU", "PN3RIGRL", "NP3RIGLL", "NP3FTAPR", "NP3FTAPL", "NP3HMOVR", "NP3HMOVL", "NP3PRSPR", "NP3PRSPL", "NP3TTAPR", "NP3TTAPL", "NP3LGAGR", "NP3LGAGL", "NP3RISNG", "NP3GAIT", "NP3FRZGT", "NP3PSTBL", "NP3POSTR", "NP3BRADY", "NP3PTRMR", "NP3PTRML", "NP3KTRMR", "NP3KTRML", "NP3RTARU", "NP3RTALU", "NP3RTARL", "NP3RTALL", "NP3RTALJ", "NP3RTCON", 
                  "DYSKPRES", "DYSKIRAT", "NHY") %>% 
  mutate(
    NP3SPCH = case_when(NP3SPCH >=3 ~ "NP3SPCH_1",
                           NP3SPCH < 3 ~ "NP3SPCH_0"),
    NP3FACXP = case_when(NP3FACXP >=3 ~ "NP3FACXP_1",
                           NP3FACXP < 3 ~ "NP3FACXP_0"),
    NP3RIGN = case_when(NP3RIGN >=3 ~ "NP3RIGN_1",
                           NP3RIGN < 3 ~ "NP3RIGN_0"),
    NP3RIGRU = case_when(NP3RIGRU >=3 ~ "NP3RIGRU_1",
                           NP3RIGRU < 3 ~ "NP3RIGRU_0"),
    NP3RIGLU = case_when(NP3RIGLU >=3 ~ "NP3RIGLU_1",
                           NP3RIGLU < 3 ~ "NP3RIGLU_0"),
    PN3RIGRL = case_when(PN3RIGRL >=3 ~ "PN3RIGRL_1",
                           PN3RIGRL < 3 ~ "PN3RIGRL_0"),
    NP3RIGLL = case_when(NP3RIGLL >=3 ~ "NP3RIGLL_1",
                           NP3RIGLL < 3 ~ "NP3RIGLL_0"),
    NP3FTAPR = case_when(NP3FTAPR >=3 ~ "NP3FTAPR_1",
                           NP3FTAPR < 3 ~ "NP3FTAPR_0"),
    NP3FTAPL = case_when(NP3FTAPL >=3 ~ "NP3FTAPL_1",
                           NP3FTAPL < 3 ~ "NP3FTAPL_0"),
    NP3HMOVR = case_when(NP3HMOVR >=3 ~ "NP3HMOVR_1",
                           NP3HMOVR < 3 ~ "NP3HMOVR_0"),
    NP3HMOVL = case_when(NP3HMOVL >=3 ~ "NP3HMOVL_1",
                           NP3HMOVL < 3 ~ "NP3HMOVL_0"),
    NP3PRSPR = case_when(NP3PRSPR >=3 ~ "NP3PRSPR_1",
                           NP3PRSPR < 3 ~ "NP3PRSPR_0"),
    NP3PRSPL = case_when(NP3PRSPL >=3 ~ "NP3PRSPL_1",
                           NP3PRSPL < 3 ~ "NP3PRSPL_0"),
    NP3TTAPR = case_when(NP3TTAPR >=3 ~ "NP3TTAPR_1",
                           NP3TTAPR < 3 ~ "NP3TTAPR_0"),
    NP3TTAPL = case_when(NP3TTAPL >=3 ~ "NP3TTAPL_1",
                           NP3TTAPL < 3 ~ "NP3TTAPL_0"),
    NP3LGAGR = case_when(NP3LGAGR >=3 ~ "NP3LGAGR_1",
                           NP3LGAGR < 3 ~ "NP3LGAGR_0"),
    NP3LGAGL = case_when(NP3LGAGL >=3 ~ "NP3LGAGL_1",
                           NP3LGAGL < 3 ~ "NP3LGAGL_0"),
    NP3RISNG = case_when(NP3RISNG >=3 ~ "NP3RISNG_1",
                           NP3RISNG < 3 ~ "NP3RISNG_0"),
    NP3GAIT = case_when(NP3GAIT >=3 ~ "NP3GAIT_1",
                           NP3GAIT < 3 ~ "NP3GAIT_0"),
    NP3FRZGT = case_when(NP3FRZGT >=3 ~ "NP3FRZGT_1",
                           NP3FRZGT < 3 ~ "NP3FRZGT_0"),
    NP3PSTBL = case_when(NP3PSTBL >=3 ~ "NP3PSTBL_1",
                           NP3PSTBL < 3 ~ "NP3PSTBL_0"),
    NP3POSTR = case_when(NP3POSTR >=3 ~ "NP3POSTR_1",
                           NP3POSTR < 3 ~ "NP3POSTR_0"),
    NP3BRADY = case_when(NP3BRADY >=3 ~ "NP3BRADY_1",
                           NP3BRADY < 3 ~ "NP3BRADY_0"),
    NP3PTRMR = case_when(NP3PTRMR >=3 ~ "NP3PTRMR_1",
                           NP3PTRMR < 3 ~ "NP3PTRMR_0"),
    NP3PTRML = case_when(NP3PTRML >=3 ~ "NP3PTRML_1",
                           NP3PTRML < 3 ~ "NP3PTRML_0"),
    NP3KTRMR = case_when(NP3KTRMR >=3 ~ "NP3KTRMR_1",
                           NP3KTRMR < 3 ~ "NP3KTRMR_0"),
    NP3KTRML = case_when(NP3KTRML >=3 ~ "NP3KTRML_1",
                           NP3KTRML < 3 ~ "NP3KTRML_0"),
    NP3RTARU = case_when(NP3RTARU >=3 ~ "NP3RTARU_1",
                           NP3RTARU < 3 ~ "NP3RTARU_0"),
    NP3RTALU = case_when(NP3RTALU >=3 ~ "NP3RTALU_1",
                           NP3RTALU < 3 ~ "NP3RTALU_0"),
    NP3RTARL = case_when(NP3RTARL >=3 ~ "NP3RTARL_1",
                           NP3RTARL < 3 ~ "NP3RTARL_0"),
    NP3RTALL = case_when(NP3RTALL >=3 ~ "NP3RTALL_1",
                           NP3RTALL < 3 ~ "NP3RTALL_0"),
    NP3RTALJ = case_when(NP3RTALJ >=3 ~ "NP3RTALJ_1",
                           NP3RTALJ < 3 ~ "NP3RTALJ_0"),
    NP3RTCON = case_when(NP3RTCON >=3 ~ "NP3RTCON_1",
                           NP3RTCON < 3 ~ "NP3RTCON_0"),
    DYSKPRES = case_when(DYSKPRES == "1" ~ "DYSKPRES_1",
                       DYSKPRES == "0" ~ "DYSKPRES_0"),
    DYSKIRAT = case_when(DYSKIRAT == "1" ~ "DYSKIRAT_1",
                       DYSKIRAT == "0" ~ "DYSKIRAT_0"),
    NHY = case_when(NHY >=3 ~ "NP4DYSTN_1",
                    NHY < 3 ~ "NP4DYSTN_0"))

updrs4 = read_csv("./data/Motor___MDS-UPDRS/MDS_UPDRS_Part_IV.csv")%>% select("PATNO", "EVENT_ID", "NP4WDYSK", "NP4DYSKI", "NP4OFF", "NP4FLCTI", "NP4FLCTX", "NP4DYSTN")%>% 
  mutate(
    NP4WDYSK = case_when(NP4WDYSK >=3 ~ "NP4WDYSK_1",
                           NP4WDYSK < 3 ~ "NP4WDYSK_0"),
    NP4DYSKI = case_when(NP4DYSKI >=3 ~ "NP4DYSKI_1",
                           NP4DYSKI < 3 ~ "NP4DYSKI_0"),
    NP4OFF = case_when(NP4OFF >=3 ~ "NP4OFF_1",
                           NP4OFF < 3 ~ "NP4OFF_0"),
    NP4FLCTI = case_when(NP4FLCTI >=3 ~ "NP4FLCTI_1",
                           NP4FLCTI < 3 ~ "NP4FLCTI_0"),
    NP4FLCTX = case_when(NP4FLCTX >=3 ~ "NP4FLCTX_1",
                           NP4FLCTX < 3 ~ "NP4FLCTX_0"),
    NP4DYSTN = case_when(NP4DYSTN >=3 ~ "NP4DYSTN_1",
                           NP4DYSTN < 3 ~ "NP4DYSTN_0")
    )
```

### anxiety: stai 
```{r}
stai = read_csv("./data/Non-motor_Assessments/State-Trait_Anxiety_Inventory.csv") %>% select("PATNO", "EVENT_ID", "STAIAD1", "STAIAD2", "STAIAD3", "STAIAD4", "STAIAD5", "STAIAD6", "STAIAD7", "STAIAD8", "STAIAD9", "STAIAD10", "STAIAD11", "STAIAD12", "STAIAD13", "STAIAD14", "STAIAD15", "STAIAD16", "STAIAD17", "STAIAD18", "STAIAD19", "STAIAD20", "STAIAD21", "STAIAD22", "STAIAD23", "STAIAD24", "STAIAD25", "STAIAD26", "STAIAD27", "STAIAD28", "STAIAD29", "STAIAD30", "STAIAD31", "STAIAD32", "STAIAD33", "STAIAD34", "STAIAD35", "STAIAD36", "STAIAD37", "STAIAD38", "STAIAD39", "STAIAD40") %>% 
  mutate(
    STAIAD1 = case_when(STAIAD1 >=3 ~ "STAIAD1_1",
                           STAIAD1 < 3 ~ "STAIAD1_0"),
    STAIAD2 = case_when(STAIAD2 >=3 ~ "STAIAD2_1",
                           STAIAD2 < 3 ~ "STAIAD2_0"),
    STAIAD3 = case_when(STAIAD3 >=3 ~ "STAIAD3_1",
                           STAIAD3 < 3 ~ "STAIAD3_0"),
    STAIAD4 = case_when(STAIAD4 >=3 ~ "STAIAD4_1",
                           STAIAD4 < 3 ~ "STAIAD4_0"),
    STAIAD5 = case_when(STAIAD5 >=3 ~ "STAIAD5_1",
                           STAIAD5 < 3 ~ "STAIAD5_0"),
    STAIAD6 = case_when(STAIAD6 >=3 ~ "STAIAD6_1",
                           STAIAD6 < 3 ~ "STAIAD6_0"),
    STAIAD7 = case_when(STAIAD7 >=3 ~ "STAIAD7_1",
                           STAIAD7 < 3 ~ "STAIAD7_0"),
    STAIAD8 = case_when(STAIAD8 >=3 ~ "STAIAD8_1",
                           STAIAD8 < 3 ~ "STAIAD8_0"),
    STAIAD9 = case_when(STAIAD9 >=3 ~ "STAIAD9_1",
                           STAIAD9 < 3 ~ "STAIAD9_0"),
    STAIAD10 = case_when(STAIAD10 >=3 ~ "STAIAD10_1",
                           STAIAD10 < 3 ~ "STAIAD10_0"),
    STAIAD11 = case_when(STAIAD11 >=3 ~ "STAIAD11_1",
                           STAIAD11 < 3 ~ "STAIAD11_0"),
    STAIAD12 = case_when(STAIAD12 >=3 ~ "STAIAD12_1",
                           STAIAD12 < 3 ~ "STAIAD12_0"),
    STAIAD13 = case_when(STAIAD13 >=3 ~ "STAIAD13_1",
                           STAIAD13 < 3 ~ "STAIAD13_0"),
    STAIAD14 = case_when(STAIAD14 >=3 ~ "STAIAD14_1",
                           STAIAD14 < 3 ~ "STAIAD14_0"),
    STAIAD15 = case_when(STAIAD15 >=3 ~ "STAIAD15_1",
                           STAIAD15 < 3 ~ "STAIAD15_0"),
    STAIAD16 = case_when(STAIAD16 >=3 ~ "STAIAD16_1",
                           STAIAD16 < 3 ~ "STAIAD16_0"),
    STAIAD17 = case_when(STAIAD17 >=3 ~ "STAIAD17_1",
                           STAIAD17 < 3 ~ "STAIAD17_0"),
    STAIAD18 = case_when(STAIAD18 >=3 ~ "STAIAD18_1",
                           STAIAD18 < 3 ~ "STAIAD18_0"),
    STAIAD19 = case_when(STAIAD19 >=3 ~ "STAIAD19_1",
                           STAIAD19 < 3 ~ "STAIAD19_0"),
    STAIAD20 = case_when(STAIAD20 >=3 ~ "STAIAD20_1",
                           STAIAD20 < 3 ~ "STAIAD20_0"),
    STAIAD21 = case_when(STAIAD21 >=3 ~ "STAIAD21_1",
                           STAIAD21 < 3 ~ "STAIAD21_0"),
    STAIAD22 = case_when(STAIAD22 >=3 ~ "STAIAD22_1",
                           STAIAD22 < 3 ~ "STAIAD22_0"),
    STAIAD23 = case_when(STAIAD23 >=3 ~ "STAIAD23_1",
                           STAIAD23 < 3 ~ "STAIAD23_0"),
    STAIAD24 = case_when(STAIAD24 >=3 ~ "STAIAD24_1",
                           STAIAD24 < 3 ~ "STAIAD24_0"),
    STAIAD25 = case_when(STAIAD25 >=3 ~ "STAIAD25_1",
                           STAIAD25 < 3 ~ "STAIAD25_0"),
    STAIAD26 = case_when(STAIAD26 >=3 ~ "STAIAD26_1",
                           STAIAD26 < 3 ~ "STAIAD26_0"),
    STAIAD27 = case_when(STAIAD27 >=3 ~ "STAIAD27_1",
                           STAIAD27 < 3 ~ "STAIAD27_0"),
    STAIAD28 = case_when(STAIAD28 >=3 ~ "STAIAD28_1",
                           STAIAD28 < 3 ~ "STAIAD28_0"),
    STAIAD29 = case_when(STAIAD29 >=3 ~ "STAIAD29_1",
                           STAIAD29 < 3 ~ "STAIAD29_0"),
    STAIAD30 = case_when(STAIAD30 >=3 ~ "STAIAD30_1",
                           STAIAD30 < 3 ~ "STAIAD30_0"),
    STAIAD31 = case_when(STAIAD31 >=3 ~ "STAIAD31_1",
                           STAIAD31 < 3 ~ "STAIAD31_0"),
    STAIAD32 = case_when(STAIAD32 >=3 ~ "STAIAD32_1",
                           STAIAD32 < 3 ~ "STAIAD32_0"),
    STAIAD33 = case_when(STAIAD33 >=3 ~ "STAIAD33_1",
                           STAIAD33 < 3 ~ "STAIAD33_0"),
    STAIAD34 = case_when(STAIAD34 >=3 ~ "STAIAD34_1",
                           STAIAD34 < 3 ~ "STAIAD34_0"),
    STAIAD35 = case_when(STAIAD35 >=3 ~ "STAIAD35_1",
                           STAIAD35 < 3 ~ "STAIAD35_0"),
    STAIAD36 = case_when(STAIAD36 >=3 ~ "STAIAD36_1",
                           STAIAD36 < 3 ~ "STAIAD36_0"),
    STAIAD37 = case_when(STAIAD37 >=3 ~ "STAIAD37_1",
                           STAIAD37 < 3 ~ "STAIAD37_0"),
    STAIAD38 = case_when(STAIAD38 >=3 ~ "STAIAD38_1",
                           STAIAD38 < 3 ~ "STAIAD38_0"),
    STAIAD39 = case_when(STAIAD39 >=3 ~ "STAIAD39_1",
                           STAIAD39 < 3 ~ "STAIAD39_0"),
    STAIAD40 = case_when(STAIAD40 >=3 ~ "STAIAD40_1",
                           STAIAD40 < 3 ~ "STAIAD40_0")
    
  )

```

## Join

```{r}
data = full_join(demo,diag)  %>% full_join(scent) %>% full_join(stai) %>% full_join(updrs1) %>% full_join(updrs1pq) %>% full_join(updrs2pq) %>% full_join(updrs3) %>% full_join(updrs4)%>% full_join(moca)

data = base::unique(data)

data = data %>%
  group_by(PATNO, EVENT_ID) %>%
  filter(row_number() == 1) %>%
  ungroup()

write.csv(data, file = "./data/Clean_Join.csv")

```

## UPDRS

```{r}
updrs1 = read_csv("./data/Motor___MDS-UPDRS/MDS_UPDRS_Part_I.csv") %>% select("PATNO", "EVENT_ID",  "NP1COG", "NP1HALL", "NP1DPRS", "NP1ANXS", "NP1APAT", "NP1DDS")

updrs1pq = read_csv("./data/Motor___MDS-UPDRS/MDS_UPDRS_Part_I__Patient_Questionnaire.csv") %>% select("PATNO", "EVENT_ID", "NP1SLPN", "NP1SLPD", "NP1PAIN", "NP1URIN", "NP1CNST", "NP1LTHD", "NP1FATG")

updrs2pq = read_csv("./data/Motor___MDS-UPDRS/MDS_UPDRS_Part_II__Patient_Questionnaire.csv")%>% select("PATNO", "EVENT_ID", "NP2SPCH", "NP2SALV", "NP2SWAL", "NP2EAT", "NP2DRES", "NP2HYGN", "NP2HWRT", "NP2HOBB", "NP2TURN", "NP2TRMR", "NP2RISE", "NP2WALK", "NP2FREZ")

updrs3 = read_csv("./data/Motor___MDS-UPDRS/MDS_UPDRS_Part_III.csv")%>% select("PATNO", "EVENT_ID", "NP3SPCH", "NP3FACXP", "NP3RIGN", "NP3RIGRU", "NP3RIGLU", "PN3RIGRL", "NP3RIGLL", "NP3FTAPR", "NP3FTAPL", "NP3HMOVR", "NP3HMOVL", "NP3PRSPR", "NP3PRSPL", "NP3TTAPR", "NP3TTAPL", "NP3LGAGR", "NP3LGAGL", "NP3RISNG", "NP3GAIT", "NP3FRZGT", "NP3PSTBL", "NP3POSTR", "NP3BRADY", "NP3PTRMR", "NP3PTRML", "NP3KTRMR", "NP3KTRML", "NP3RTARU", "NP3RTALU", "NP3RTARL", "NP3RTALL", "NP3RTALJ", "NP3RTCON", 
                  "DYSKPRES", "DYSKIRAT", "NHY") 

updrs4 = read_csv("./data/Motor___MDS-UPDRS/MDS_UPDRS_Part_IV.csv")%>% select("PATNO", "EVENT_ID", "NP4WDYSK", "NP4DYSKI", "NP4OFF", "NP4FLCTI", "NP4FLCTX", "NP4DYSTN")

UPDRS = full_join(updrs1, updrs1pq) %>% full_join(updrs2pq) %>% full_join(updrs3) %>% full_join(updrs4) %>% base::unique()

UPDRS = UPDRS %>%
  group_by(PATNO, EVENT_ID) %>%
  filter(row_number() == 1) %>%
  ungroup()

write.csv(UPDRS, file = "./data/UPDRS.csv")
```

